---------------------------------------------------
-- Create database
---------------------------------------------------
DROP DATABASE IF EXISTS "full-stack-ecommerce";
CREATE DATABASE "full-stack-ecommerce";

DROP TABLE IF EXISTS "product";
DROP TABLE IF EXISTS "product_category";

---------------------------------------------------
-- Create table product_category
---------------------------------------------------
CREATE TABLE IF NOT EXISTS "product_category"
(
    id            int          NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name varchar(255) NOT NULL
);

---------------------------------------------------
-- Create table product
---------------------------------------------------
CREATE TABLE IF NOT EXISTS "product"
(
    id             int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku            varchar(255)   DEFAULT NULL,
    name           varchar(255)   DEFAULT NULL,
    description    varchar(255)   DEFAULT NULL,
    unit_price     decimal(13, 2) DEFAULT NULL,
    image_url      varchar(255)   DEFAULT NULL,
    active         bit            DEFAULT B'1',
    units_in_stock int            DEFAULT NULL,
    date_created   timestamp      DEFAULT NULL,
    last_updated   timestamp      DEFAULT NULL,
    category_id    int REFERENCES product_category (id)
);

---------------------------------------------------
-- Fill out product_category table with some data
---------------------------------------------------
INSERT INTO product_category(category_name)
VALUES ('BOOKS');

---------------------------------------------------
-- Fill out product table with some data
---------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock,
                     unit_price, category_id, date_created)
VALUES ('BOOK-TECH-1000', 'JavaScript - The Fun Parts', 'Learn JavaScript',
        'assets/images/products/placeholder.png'
           , B'1', 100, 19.99, 1, NOW());

INSERT INTO product (sku, name, description, image_url, active, units_in_stock,
                     unit_price, category_id, date_created)
VALUES ('BOOK-TECH-1001', 'Spring Framework Tutorial', 'Learn Spring',
        'assets/images/products/placeholder.png'
           , B'1', 100, 29.99, 1, NOW());

INSERT INTO product (sku, name, description, image_url, active, units_in_stock,
                     unit_price, category_id, date_created)
VALUES ('BOOK-TECH-1002', 'Kubernetes - Deploying Containers', 'Learn Kubernetes',
        'assets/images/products/placeholder.png'
           , B'1', 100, 24.99, 1, NOW());

INSERT INTO product (sku, name, description, image_url, active, units_in_stock,
                     unit_price, category_id, date_created)
VALUES ('BOOK-TECH-1003', 'Internet of Things (IoT) - Getting Started', 'Learn IoT',
        'assets/images/products/placeholder.png'
           , B'1', 100, 29.99, 1, NOW());

INSERT INTO product (sku, name, description, image_url, active, units_in_stock,
                     unit_price, category_id, date_created)
VALUES ('BOOK-TECH-1004', 'The Go Programming Language: A to Z', 'Learn Go',
        'assets/images/products/placeholder.png'
           , B'1', 100, 24.99, 1, NOW());